steps:
  # Build the Docker image in which we'll build the static files
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/sh
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/frontend:latest \
        --build-arg VITE_APP_BACKEND_URL=${_BACKEND_URL} \
         -f Dockerfile.prod .
  # Extract the static files from the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "create",
        "--name",
        "temp-container",
        "gcr.io/$PROJECT_ID/frontend:latest",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["cp", "temp-container:/exported_files", "./dist"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["rm", "temp-container"]
  # Install Firebase CLI using NPM and deploy the static files to Firebase Hosting
  - name: "node:latest"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm install -g firebase-tools
        firebase use --add $PROJECT_ID
        firebase deploy --only hosting --public dist

# @docs: https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
substitutions:
  _BACKEND_URL: "http://localhost/api"
