# Base stage
FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack use pnpm@latest
COPY . /opt/backend
WORKDIR /opt/backend

# Dependencies stage
FROM base AS deps
RUN pnpm install --prod --frozen-lockfile

# Executable stage
FROM base
COPY --from=deps /opt/backend/node_modules /opt/backend/node_modules
ENV NODE_ENV=prod
ENV PORT=80
ENV HOST=0.0.0.0

EXPOSE 80
CMD ["pnpm", "start:prod"]
